import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';
import { Lato } from 'next/font/google';

const lato = Lato({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Ash Coin - Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <div className="border-b-2 border-solid border-grey">
          <Navbar />
        </div>
        {children}
        <div className="border-t-2 border-solid border-grey">
          <Footer />
        </div>
      </body>
    </html>
  );
}
